/**
 * RFC 8785 (JCS) Cross-Implementation Conformance
 *
 * Locks the TypeScript canonicalizeJson output to the Python rfc8785
 * reference library byte-for-byte. The golden vectors in
 * fixtures/jcs-rfc8785-vectors.json were generated by rfc8785.dumps(),
 * so a passing run proves the TS and Python SDKs canonicalize identically.
 *
 * This turns the "identical hashes across platforms" guarantee in
 * crypto/index.ts from an assertion into evidence, and is the conformance
 * basis for the RFC-8785-normative requirement in x402 spec PR #2666.
 */
import { describe, it, expect } from 'vitest';
import { canonicalizeJson } from '@nobulex/crypto';

import golden from '../../fixtures/jcs-rfc8785-vectors.json';

describe('RFC 8785 JCS cross-implementation (TS vs Python rfc8785)', () => {
  golden.vectors.forEach((vector, i) => {
    it(`vector ${i}: TS canonical form is byte-identical to rfc8785`, () => {
      expect(canonicalizeJson(vector.input)).toBe(vector.canonical);
    });
  });

  it('rejects integers beyond the safe-integer domain (matches rfc8785 IntegerDomainError)', () => {
    // 12345678901234567890 is greater than 2^53. The Python rfc8785 lib
    // raises IntegerDomainError; canonicalizeJson must throw rather than
    // silently lose precision and sign corrupted bytes.
    expect(() => canonicalizeJson({ big: 12345678901234567890 })).toThrow(
      /safe integer domain/,
    );
  });

  it('rejects non-finite numbers', () => {
    expect(() => canonicalizeJson({ x: Infinity })).toThrow(/non-finite/);
    expect(() => canonicalizeJson({ x: NaN })).toThrow(/non-finite/);
  });

  it('is deterministic regardless of input key order', () => {
    expect(canonicalizeJson({ b: 2, a: 1 })).toBe(
      canonicalizeJson({ a: 1, b: 2 }),
    );
  });
});
