#!/usr/bin/env node
/**
 * Compile Solidity contracts with solc and generate ABIs + TypeScript bindings.
 */
const solc = require('solc');
const fs = require('fs');
const path = require('path');

const CONTRACTS_DIR = path.resolve(__dirname, '../solidity');
const OUTPUT_DIR = path.resolve(__dirname, '../src/generated');

// Read all .sol files
const sources = {};
for (const file of fs.readdirSync(CONTRACTS_DIR)) {
  if (file.endsWith('.sol')) {
    sources[file] = { content: fs.readFileSync(path.join(CONTRACTS_DIR, file), 'utf-8') };
  }
}

const input = {
  language: 'Solidity',
  sources,
  settings: {
    outputSelection: {
      '*': {
        '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object'],
      },
    },
    optimizer: { enabled: true, runs: 200 },
  },
};

// Resolve imports
function findImports(importPath) {
  const full = path.resolve(CONTRACTS_DIR, importPath);
  if (fs.existsSync(full)) {
    return { contents: fs.readFileSync(full, 'utf-8') };
  }
  return { error: `File not found: ${importPath}` };
}

console.log('Compiling Solidity contracts...');
const output = JSON.parse(solc.compile(JSON.stringify(input), { import: findImports }));

// Check for errors
if (output.errors) {
  const errors = output.errors.filter(e => e.severity === 'error');
  if (errors.length > 0) {
    console.error('Compilation errors:');
    for (const err of errors) {
      console.error(err.formattedMessage);
    }
    process.exit(1);
  }
  // Print warnings
  for (const warn of output.errors.filter(e => e.severity === 'warning')) {
    console.warn('Warning:', warn.message);
  }
}

// Ensure output directory
fs.mkdirSync(OUTPUT_DIR, { recursive: true });

// Extract artifacts
const artifacts = {};
for (const [fileName, contracts] of Object.entries(output.contracts)) {
  for (const [contractName, contract] of Object.entries(contracts)) {
    const abi = contract.abi;
    const bytecode = contract.evm?.bytecode?.object || '';
    artifacts[contractName] = { abi, bytecode };

    // Write ABI JSON
    fs.writeFileSync(
      path.join(OUTPUT_DIR, `${contractName}.abi.json`),
      JSON.stringify(abi, null, 2),
    );
    console.log(`  ✓ ${contractName}.abi.json (${abi.length} entries)`);
  }
}

// Generate TypeScript bindings
let tsBindings = `/**
 * Auto-generated TypeScript bindings for Nobulex Solidity contracts.
 * Generated by scripts/compile.cjs — do not edit manually.
 */

`;

for (const [name, artifact] of Object.entries(artifacts)) {
  const abiVar = `${name.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase()}_ABI`;
  tsBindings += `/** ABI for the ${name} contract. */\n`;
  tsBindings += `export const ${abiVar} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
  tsBindings += `/** Bytecode for the ${name} contract. */\n`;
  tsBindings += `export const ${name.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase()}_BYTECODE = '${artifact.bytecode}';\n\n`;

  // Generate TypeScript interface for contract functions
  const functions = artifact.abi.filter(e => e.type === 'function');
  const events = artifact.abi.filter(e => e.type === 'event');

  tsBindings += `/** Function signatures for ${name}. */\n`;
  tsBindings += `export const ${name}Functions = {\n`;
  for (const fn of functions) {
    const inputTypes = fn.inputs.map(i => `${i.name}: ${solidityToTs(i.type)}`).join(', ');
    tsBindings += `  /** ${fn.name}(${fn.inputs.map(i => i.type).join(', ')}) */\n`;
    tsBindings += `  ${fn.name}: '${fn.name}(${fn.inputs.map(i => i.type).join(',')})' as const,\n`;
  }
  tsBindings += `} as const;\n\n`;

  tsBindings += `/** Event signatures for ${name}. */\n`;
  tsBindings += `export const ${name}Events = {\n`;
  for (const ev of events) {
    tsBindings += `  ${ev.name}: '${ev.name}(${ev.inputs.map(i => i.type).join(',')})' as const,\n`;
  }
  tsBindings += `} as const;\n\n`;
}

fs.writeFileSync(path.join(OUTPUT_DIR, 'index.ts'), tsBindings);
console.log(`\n✓ Generated TypeScript bindings: src/generated/index.ts`);
console.log(`✓ Compilation complete: ${Object.keys(artifacts).length} contracts`);

function solidityToTs(type) {
  if (type === 'uint256') return 'bigint';
  if (type === 'address') return 'string';
  if (type === 'bytes32') return 'string';
  if (type === 'string') return 'string';
  if (type === 'bool') return 'boolean';
  return 'unknown';
}
